version: '3.2'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=opencart
      - MYSQL_ROOT_PASSWORD=change_to_secure_password
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
  opencart:
    build: .
    container_name: opencart
    hostname: opencart
    restart: always
    ports:
      - '1337:80'
      - '1338:443'
    volumes:
      - opencart_html:/var/www
    depends_on:
      - mysql
volumes:
  mysql_data:
    driver: local
  opencart_html:
    driver: local